apiVersion: v1
kind: Service
metadata:
  name: swiggi-clone-service
  namespace: swiggi-clone
spec:
  type: NodePort
  selector:
    app: swiggi-clone
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001

